# Generated by Django 4.1.4 on 2022-12-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=12, verbose_name="班级名称")),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("like", models.CharField(max_length=8, verbose_name="学生爱好")),
                ("blood", models.CharField(max_length=8, verbose_name="学生血型")),
                ("email", models.CharField(max_length=32, verbose_name="学生邮箱")),
                ("create_time", models.DateField(auto_now=True, verbose_name="学生报名时间")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=8, verbose_name="教师姓名")),
                ("age", models.IntegerField(verbose_name="教师年龄")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=8, verbose_name="学生姓名")),
                ("age", models.IntegerField(verbose_name="学生年龄")),
                (
                    "gender",
                    models.CharField(default="男", max_length=1, verbose_name="学生性别"),
                ),
                (
                    "addr",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="学生地址"
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.class",
                    ),
                ),
                (
                    "student_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.studentinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ManyToManyField(to="app.teacher"),
        ),
    ]
